### ISSUE TITLE
Error when login with GitHub

### ISSUE THREAD

**Issue by RomanKolosov** [implode-io/implode.io#2]
Hello!
I have error when try login with GitHub.

 
>Laravel \ Socialite \ Two \ InvalidStateException
>No message

Fixed please this problem, and change APP_DEBUG to false in .env file :)

Good Luck!

**Comment by sergey89d** [comment]
I also have an error

**Comment by andrey-helldar** [comment]
+1

**Comment by z-song** [comment]
@RomanKolosov @sergey89d @andrey-helldar It should be fixed now!

**Comment by sergey89d** [comment]
@z-song working

**Comment by epifanov-sergey** [comment]
I still have an error. When i'm redirecting on https://implode.io/login/github , i'm getting 500 error code

**Comment by z-song** [comment]
@epifanov-sergey Please try again later

**Comment by RomanKolosov** [comment]
@z-song Thank you, all work.
